"""Add Teacher table

Revision ID: 393f31cd4846
Revises: 50e48babcba4
Create Date: 2025-05-24 09:29:07.244954

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '393f31cd4846'
down_revision = '50e48babcba4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teacher',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('teacher')
    # ### end Alembic commands ###
