"""Link Course to Teacher and add relationship

Revision ID: 541c08fbb334
Revises: 393f31cd4846
Create Date: 2025-05-24 09:32:30.296650

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '541c08fbb334'
down_revision = '393f31cd4846'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_course_teacher_id', 'teacher', ['teacher_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.drop_constraint('fk_course_teacher_id', type_='foreignkey')

    # ### end Alembic commands ###
